matrix:
  include:

    - os: linux
      env: UBUNTU_TEST_VERSION=14 USE_LCM=ON MAKE_PACKAGE=ON MAKE_DOCS=ON

    - os: linux
      env: UBUNTU_TEST_VERSION=16 USE_LCM=ON MAKE_PACKAGE=ON

    - os: linux
      env: UBUNTU_TEST_VERSION=14

    - os: linux
      env: UBUNTU_TEST_VERSION=14 USE_LCM=ON USE_LCMGL=ON USE_LIBBOT=ON

    - os: osx
      osx_image: xcode7.3
      env: USE_LCM=ON USE_LIBBOT=OFF USE_LCMGL=OFF MAKE_PACKAGE=ON


language: generic
dist: trusty
sudo: required

services:
  - docker

notifications:
  email: false

virtualenv:
  system_site_packages: true

branches:
  only:
    - master
    - test

install: true

script:
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then distro/travis/test_main.sh ; else distro/travis/test_docker.sh ; fi
